#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: sudo bash setup_agent.sh <LOG_SERVER_IP_OR_DNS>"
  exit 1
fi

LOG_SERVER="$1"
CONF="/etc/rsyslog.d/99-central-forward.conf"

echo "[*] Installing rsyslog client config to forward logs to ${LOG_SERVER}:6514"

# Write config with the provided server
cat > "$CONF" <<EOF
# Auto-generated by setup_agent.sh
template(name="DynAuthFmt" type="string"
         string="%HOSTNAME% %syslogtag%%msg:::sp-if-no-1st-sp %msg%\n")

*.* @@${LOG_SERVER}:6514;DynAuthFmt
EOF

systemctl restart rsyslog
echo "[+] rsyslog restarted. This host now forwards logs to ${LOG_SERVER}:6514"
